---
title: "ManuscriptNHB-ROC-AUC-featureExtraction"
output: html_notebook
---
All feature importance plots and ROC analysis code for the Manuscript titled: ""

```{r}
#Load required libraries 
library(rstatix)
library(plotrix)
library(dplyr)
library(tidyr)
library(tidyverse)
library(psych)
library(stargazer)
library(gtsummary)
library(ggpubr)
library(ggExtra)
library(cutpointr)
library(pROC)
library(plotROC)
library(caret)
library(randomForest)
library(ggplot2)
library(mice)
```
#Boruta function
```{r include=FALSE}
 # Boruta Processing
  # =================
  # from: https://stackoverflow.com/questions/73415232/how-to-use-ggplot2-to-plot-box-plots-from-borutas-results-in-r
  process_the_Boruta_data <- function(x, whichShadow=c(FALSE,FALSE,FALSE),
                                      colCode=c('green','yellow','red','blue', "darkslategray","ivory4" ),
                                      col=NULL) {
    if(is.null(x$ImpHistory))
      stop('Importance history was not stored during the Boruta run.')
    
    #Removal of -Infs and conversion to a list
    lz <- lapply(1:ncol(x$ImpHistory),
                 function(i) x$ImpHistory[is.finite(x$ImpHistory[,i]),i])
    colnames(x$ImpHistory) -> names(lz)
    
    #Selection of shadow meta-attributes
    numShadow <- sum(whichShadow)
    lz[c(rep(TRUE,length(x$finalDecision)),whichShadow)] -> lz
    
    generateCol<-function(x,colCode,col,numShadow){
      #Checking arguments
      if(is.null(col) & length(colCode)!=6)
        stop('colCode should have 4 elements.')
      #Generating col
      if(is.null(col)){
        rep(colCode[4],length(x$finalDecision)+numShadow)->cc
        cc[c(x$finalDecision=='Confirmed',rep(FALSE,numShadow))]<-colCode[1]
        cc[c(x$finalDecision=='Tentative',rep(FALSE,numShadow))]<-colCode[2]
        cc[c(x$finalDecision=='Rejected',rep(FALSE,numShadow))]<-colCode[3]
        col=cc
      }
      return(col)
    }
    
    #Generating color vector
    col <- generateCol(x, colCode, col, numShadow)
     
    #Ordering boxes due to attribute median importance
    ii<-order(sapply(lz,stats::median))
    lz[ii] -> lz
    col <- col[ii]
    lz_df <- do.call(rbind.data.frame, lz)
    df <- as.data.frame(t(lz_df))
    names(df) <- names(lz)
    rownames(df) <- NULL
    return(df)
  }
```

```{r}
# load df_imputed and deidentified data 
df_risk_imputed <- read_csv('/Users/maharamamurthy/Library/CloudStorage/GoogleDrive-maha10@stanford.edu/My Drive/VisualMeasuresAsLanguageAgnosticScreeners/NHB/N_Communications/data/df_risk_imputed.csv')


```

REDefine risk and risk year later 

```{r}
df_risk_imputed <- df_risk_imputed %>% rename(c(LetAbilitySS=RVP_LT0,
                                                        pseAbilitySS=RVP_PT0 ,
                                                      MPabilitySS= GMC_T0))
```


```{r}
set.seed(112)
percentile_20 <- quantile(df_risk_imputed$wcj_lwi_ss_2023, probs = 0.2, na.rm = TRUE)
percentile_20
df_risk_imputed <- df_risk_imputed %>%
    mutate(risk = ifelse(wcj_lwi_ss_2023 <= percentile_20, 1, 0))

percentile_20 <- quantile(df_risk_imputed$wcj_lwi_ss_2024, probs = 0.2, na.rm = TRUE)
percentile_20
df_risk_imputed <- df_risk_imputed %>%
    mutate(riskYL = ifelse(wcj_lwi_ss_2024 <= percentile_20, 1, 0))
```


```{r}
df_risk_K_long <- df_risk_imputed %>% filter(grade_2023 ==0) 
# G1
df_risk_1_long <- df_risk_imputed %>% filter(grade_2023 ==1) 
```

#K
```{r}
set.seed(56544)
# Load the df_risk_K and 1 from the df_risk from LPA_manuscript imputed df
#predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat", "rao", "dgs")
#predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat", "rao", "del_ucat", "ble_ucat", "dgs", "nwr_ucat")
predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat_T0", "rao_T0", "del_ucat_T0", "ble_ucat_T0", "dgs_T0", "nwr_ucat_T0")
name_mapping <- c(
  evo_ucat_T0 = "Vocabulary",
  dgs_T0 = "Digit Span",
  LetAbilitySS="MEP-L",
  pseAbilitySS="MEP-P",
  MPabilitySS ="Motion",
  rao_T0 = "Rapid Automatic Naming",
  lnc_T0 = "Letter naming",
  srt_ucat_T0 = "Sentence Repetition",
  nwr_ucat_T0 = "Non-word Repetition",
  del_ucat_T0 = "Deletion",
  ble_ucat_T0 = "Blending"
)

df_risk_K_imputed <- df_risk_K_long %>% select(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, risk) %>% filter(complete.cases(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,risk)) 

df_risk <- df_risk_K_imputed

boruta_result <- Boruta(risk ~ ., data = df_risk, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)

# Plot the data:
plot1 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot1
```
# G1 
```{r}
set.seed(5694)
# Load the df_risk_K and 1 from the df_risk from LPA_manuscript imputed df

predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat_T0", "rao_T0", "del_ucat_T0", "evo_ucat_T0", "dgs_T0", "nwr_ucat_T0")
name_mapping <- c(
  evo_ucat_T0 = "Vocabulary",
  dgs_T0 = "Digit Span",
  LetAbilitySS="MEP-L",
  pseAbilitySS="MEP-P",
  MPabilitySS ="Motion",
  rao_T0 = "Rapid Automatic Naming",
  lnc_T0 = "Letter naming",
  srt_ucat_T0 = "Sentence Repetition",
  nwr_ucat_T0 = "Non-word Repetition",
  del_ucat_T0 = "Deletion",
  ble_ucat_T0 = "Blending"
)

df_risk_1_imputed <- df_risk_1_long %>% select(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, risk) %>% filter(complete.cases(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,risk)) 

df_risk <- df_risk_1_imputed

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(risk ~ ., data = df_risk, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)

# Plot the data:
plot2 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot2
```
#K-a year later
```{r}
set.seed(5654)
# Load the df_risk_K and 1 from the df_risk from LPA_manuscript imputed df

predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat_T0", "rao_T0", "del_ucat_T0", "ble_ucat_T0", "dgs_T0", "nwr_ucat_T0")
name_mapping <- c(
  evo_ucat_T0 = "Vocabulary",
  dgs_T0 = "Digit Span",
  LetAbilitySS="MEP-L",
  pseAbilitySS="MEP-P",
  MPabilitySS ="Motion",
  rao_T0 = "Rapid Automatic Naming",
  lnc_T0 = "Letter naming",
  srt_ucat_T0 = "Sentence Repetition",
  nwr_ucat_T0 = "Non-word Repetition",
  del_ucat_T0 = "Deletion",
  ble_ucat_T0 = "Blending"
)

df_risk_K_imputed <- df_risk_K_long %>% select(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, riskYL) %>% filter(complete.cases(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,riskYL)) 

df_risk <- df_risk_K_imputed

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(riskYL ~ ., data = df_risk, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)

# Plot the data:
plot3 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot3
```
#G1 - a year later 
```{r}
set.seed(5694)
# Load the df_risk_K and 1 from the df_risk from LPA_manuscript imputed df

predictors <- c("LetAbilitySS", "pseAbilitySS", "MPabilitySS", "srt_ucat_T0", "rao_T0", "del_ucat_T0", "evo_ucat_T0", "dgs_T0", "nwr_ucat_T0")
name_mapping <- c(
  evo_ucat_T0 = "Vocabulary",
  dgs_T0 = "Digit Span",
  LetAbilitySS="MEP-L",
  pseAbilitySS="MEP-P",
  MPabilitySS ="Motion",
  rao_T0 = "Rapid Automatic Naming",
  lnc_T0 = "Letter naming",
  srt_ucat_T0 = "Sentence Repetition",
  nwr_ucat_T0 = "Non-word Repetition",
  del_ucat_T0 = "Deletion",
  ble_ucat_T0 = "Blending"
)

df_risk_1_imputed <- df_risk_1_long %>% select(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, riskYL) %>% filter(complete.cases(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,riskYL)) 

df_risk <- df_risk_1_imputed

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(riskYL ~ ., data = df_risk, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)

# Plot the data:
plot4 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot4
```
# Now balance data using the ROSE package 
## K- balanced risk 
```{r}
# Balance the dataset using ROSE (Random Over-Sampling Examples)
library("ROSE")
set.seed(152244)  # For reproducibility

df_risk_K_imputed <- df_risk_K_long %>% select(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, risk) %>% filter(complete.cases(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,risk)) 

df_risk <- df_risk_K_imputed

balanced_data <- ROSE(risk ~ ., data = df_risk, seed = 152244)$data

# Check class distribution
table(balanced_data$risk)

## Now use this balanced table 

df_risk_K <- balanced_data

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(risk ~ ., data = df_risk_K, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)


# Plot the data:
plot5 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot5
```
## G1- balanced data

```{r}
set.seed(152244)  # For reproducibility

df_risk_1_imputed <- df_risk_1_long %>% select(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, risk) %>% filter(complete.cases(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,risk)) 

df_risk <- df_risk_1_imputed

balanced_data <- ROSE(risk ~ ., data = df_risk, seed = 152244)$data

# Check class distribution
table(balanced_data$risk)

## Now use this balanced table 

df_risk_1 <- balanced_data

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(risk ~ ., data = df_risk_1, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)


# Plot the data:
plot6 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot6
```
## K- a year later Balanced data 
```{r}
set.seed(15224)  # For reproducibility

df_risk_K_imputed <- df_risk_K_long %>% select(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, riskYL) %>% filter(complete.cases(ble_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,riskYL)) 

df_risk <- df_risk_K_imputed

balanced_data <- ROSE(riskYL ~ ., data = df_risk, seed = 15224)$data

# Check class distribution
table(balanced_data$risk)

## Now use this balanced table 

df_risk_K <- balanced_data

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(riskYL ~ ., data = df_risk_K, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)


# Plot the data:
plot7 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot7
```
## G1- a year later balanced data 
```{r}
set.seed(152244)  # For reproducibility

df_risk_1_imputed <- df_risk_1_long %>% select(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS, riskYL) %>% filter(complete.cases(evo_ucat_T0, rao_T0, del_ucat_T0, dgs_T0,nwr_ucat_T0,srt_ucat_T0, LetAbilitySS, pseAbilitySS, MPabilitySS,riskYL)) 

df_risk <- df_risk_1_imputed

balanced_data <- ROSE(riskYL ~ ., data = df_risk, seed = 152244)$data

# Check class distribution
table(balanced_data$riskYL)

## Now use this balanced table 

df_risk_1 <- balanced_data

#imp <- mice(df_risk_G1, print =FALSE, seed=1 )
#df_risk_G1 <- as.data.frame(mice::complete(imp,1))

boruta_result <- Boruta(riskYL ~ ., data = df_risk_1, doTrace = 0, maxRuns = 100, ntrees = 100)
boruta_result

# Apply the function:
boruta_clean <- process_the_Boruta_data(boruta_result)


# Plot the data:
plot8 <- boruta_clean %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = fct_reorder(name, value, median), x = value)) +
  geom_boxplot(color = "darkslategray") +
 # labs(title = "First Grade") +
  theme_bw() +
  theme(
        axis.text.x = element_text(angle = 0,
                                   vjust = 1,
                                   hjust = 1,
                                   size = 15),
         axis.text.y = element_text(size = 16),  # Added y-axis text size
        axis.title.x = element_text(size = 18)) +
labs(x = "Median importance value", y = "") +
  scale_y_discrete(labels = name_mapping)
plot8
```
## AUC and accuracy table for manuscript
```{r}
# Function to perform LOOCV for logistic regression with custom threshold - this is also Random forest so everything matches! 
set.seed(9832)
perform_loocv <- function(data, formula) {
  n <- nrow(data)
  predictions <- numeric(n)
  weight_sensitivity = 0.7
  for (i in 1:n) {
    train <- data[-i, ]
    test <- data[i, ]
    #model <- glm(formula, data = train, family = binomial)
    #predictions[i] <- predict(model, newdata = test, type = "response")
    
    model <- randomForest(formula, data = train, ntree = 100, seed = 9832)
    predictions[i] <- predict(model, newdata = test, type = "prob")[, 2]
  }
  actual <- data$risk
  roc_obj <- pROC::roc(actual, predictions)
  auc <- pROC::auc(roc_obj)
  coords <- coords(roc_obj, "all")
  index <- which.min(abs(coords$sensitivity - 0.7))
  optimal_threshold <- coords$threshold[index]
  predicted_class <- factor(ifelse(predictions <= optimal_threshold, 0, 1), levels = c(0, 1))
  actual <- factor(actual, levels = c(0, 1))
  cm <- caret::confusionMatrix(predicted_class, actual)
  ci <- pROC::ci.auc(roc_obj)
  list(
    auc = auc,
    ci_lower = ci[1],
    ci_upper = ci[3],
    accuracy = cm$overall["Accuracy"],
    sensitivity = cm$byClass["Sensitivity"],
    specificity = cm$byClass["Specificity"]
  )
}

# Function to create and evaluate models
create_models <- function(data, outcome, predictors) {
  results <- list()
  for (i in 1:length(predictors)) {
    for (combo in combn(predictors, i, simplify = FALSE)) {
      formula <- as.formula(paste("risk", "~", paste(combo, collapse = " + ")))
      model_name <- paste(combo, collapse = "_")
      results[[model_name]] <- perform_loocv(data, formula)
    }
  }
  return(results)
}

# Define predictors and outcomes
predictors1 <- c( "del_ucat", "ble_ucat", "nwr_ucat", "srt_ucat",  "dgs", "rao","LetAbilitySS", "pseAbilitySS", "MPabilitySS")    
predictors2 <- c( "del_ucat", "evo_ucat", "nwr_ucat", "srt_ucat",  "dgs", "rao","LetAbilitySS", "pseAbilitySS", "MPabilitySS")  

#outcomes <- c("wcj_lwi_ss", "wcj_wa_ss") #, "wcj_lwi_ss_24", "wcj_wa_ss_24", "wcj_c_reading_24", "wcj_c_BRS_24", "wcj_c_boardreading_24")
outcomes <- c("wcj_lwi_ss", "wcj_wa_ss", "wcj_lwi_ss_24", "wcj_wa_ss_24", "wcj_c_reading_24", "wcj_c_BRS_24", "wcj_c_boardreading_24")

# Create empty results dataframe
results_df <- data.frame(
  Risk_classification = character(),
  Grade = numeric(),
  Predictors = character(),
  AUC = numeric(),
  stringsAsFactors = FALSE
)

# Prepare data frame 
df_AUC <- df_risk_imputed %>% filter(complete.cases(grade)) %>% select(-c(lsi_ucat,lco, proxy_SES, langflu, potential_study_id, rptglng, ELStatus,risk,risk_eoy1, lnc)) 
# Loop through outcomes and grades
for (outcome in outcomes) {
# Calculate risk for this outcome
  #df_risk_AUC <- df_AUC
  df_risk_AUC <- calculate_risk(df_AUC,outcome)
  #df_risk_AUC$risk <- as.factor(df_risk_AUC$risk)
  ## Insert code to filter for ELstatus 
  #%>% filter(ELStatus == "EL")
  
  for (grade in c(0, 1)) {
    if (grade == 0) {
        predictors = predictors1
        df_temp <- df_risk_AUC %>% select(-c(evo_ucat))
        #df <- df_temp %>% filter(grade == 0)
    }
    else { predictors = predictors2
           df_temp <- df_risk_AUC %>% select(-c(ble_ucat))
           #df <- df_temp %>% filter(grade == 1)
    }
    print(grade)
    this_grade = grade;
    # Select appropriate dataframe
    df <- df_temp %>% filter(grade == this_grade)
    df$risk <- as.factor(df$risk)
    # Create and evaluate models
    models <- create_models(df, outcome, predictors)
    print(outcome)
    # Add results to dataframe
    for (model_name in names(models)) {
        print(outcome)
        results_df <- rbind(results_df, data.frame(
        Risk_classification = outcome,
        Grade = grade,
        Predictors = model_name,
        AUC = models[[model_name]]$auc,
        Accuracy = models[[model_name]]$accuracy,
        stringsAsFactors = FALSE
      ))
    }
  }
}

# Sort results by Risk_classification, Grade, and AUC
results_df <- results_df %>%
  arrange(Risk_classification, Grade, desc(AUC))
# Find the best models based on AUC and Accuracy
best_models <- results_df %>%
   #filter(Accuracy > 0.5) %>%
    mutate(
    AUC_rounded = round(AUC, 4),
    Accuracy_rounded = round(Accuracy, 4)
  ) %>%
  group_by(Grade,Risk_classification) %>%
  arrange(desc(AUC_rounded),desc(Accuracy_rounded)) %>%
  slice(1) %>%
  ungroup()
write_csv(results_df, "finalAUC-TableManuscript-allpredictors.csv")
# Print the best models for each grade
results_df <- read_csv('/Users/maharamamurthy/Library/CloudStorage/GoogleDrive-maha10@stanford.edu/My Drive/VisualMeasuresAsLanguageAgnosticScreeners/NHB/bigAUCTable2-withoutMEPL.csv')
best_models
```

